import {
  Trace,
  Span,
  Agent,
  OverviewKPIs,
  TraceStatus,
  SpanType,
} from "@/types/telemetry"

export const MOCK_AGENTS: Agent[] = [
  {
    id: "agent_customer_support",
    name: "Customer Support Agent",
    version: "v2.4.1",
    description: "Multi-turn user problem diagnosis with knowledge retrieval and tool execution.",
    defaultModel: "gpt-4o",
    traceCount: 1420,
    successRate: 0.982,
    avgLatencyMs: 840,
    p95LatencyMs: 1950,
    totalTokens: 3840000,
    totalCostUsd: 14.82,
    status: "active",
    dependencies: ["agent_doc_retriever", "agent_billing_tools"],
  },
  {
    id: "agent_sql_analyst",
    name: "Financial Data Synthesizer",
    version: "v1.9.0",
    description: "Automated warehouse SQL querying, safety guardrails, and data aggregation.",
    defaultModel: "claude-3-5-sonnet",
    traceCount: 890,
    successRate: 0.965,
    avgLatencyMs: 1420,
    p95LatencyMs: 3100,
    totalTokens: 5210000,
    totalCostUsd: 26.45,
    status: "active",
    dependencies: ["agent_db_tool", "agent_guardrail"],
  },
  {
    id: "agent_code_reviewer",
    name: "Autonomous Coding Swarm",
    version: "v3.1.0",
    description: "Multi-agent review swarm analyzing PRs, linting, security, and test runs.",
    defaultModel: "deepseek-r1",
    traceCount: 654,
    successRate: 0.941,
    avgLatencyMs: 2890,
    p95LatencyMs: 6400,
    totalTokens: 9140000,
    totalCostUsd: 18.29,
    status: "active",
    dependencies: ["agent_ast_parser", "agent_linter"],
  },
  {
    id: "agent_doc_retriever",
    name: "Vector Retrieval Agent",
    version: "v1.2.0",
    description: "Hybrid dense & sparse embedding retrieval across company knowledge base.",
    defaultModel: "text-embedding-3-small",
    traceCount: 2310,
    successRate: 0.998,
    avgLatencyMs: 190,
    p95LatencyMs: 420,
    totalTokens: 1120000,
    totalCostUsd: 2.14,
    status: "active",
  },
]

export const MOCK_TRACES: Trace[] = [
  {
    id: "tr_8f9104b2a3c7",
    name: "Customer Support / Refund Request #4912",
    agentId: "agent_customer_support",
    agentName: "Customer Support Agent",
    sessionId: "sess_user_9921",
    userId: "usr_charlie_k",
    status: "ok",
    startTime: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
    durationMs: 940,
    promptTokens: 1240,
    completionTokens: 380,
    totalTokens: 1620,
    totalCostUsd: 0.0078,
    tags: ["production", "refund-flow", "high-priority"],
    input: {
      user_message: "Can you help me cancel my annual subscription and check if I'm eligible for a refund?",
      account_id: "acc_992138",
      tier: "enterprise",
    },
    output: {
      decision: "refund_eligible",
      amount_usd: 240.0,
      reply_message: "I've checked your account. Since your annual renewal was processed 2 days ago, you are within the 14-day refund window. I've initiated the refund of $240.00.",
    },
    metadata: {
      region: "us-east-1",
      sdk_version: "asi-telemetry-py-0.8.2",
      runtime: "python3.11",
    },
    spans: [
      {
        id: "sp_root_01",
        traceId: "tr_8f9104b2a3c7",
        parentSpanId: null,
        name: "Agent Orchestration Pipeline",
        type: "agent",
        status: "ok",
        startTime: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
        durationMs: 940,
        totalTokens: 1620,
        costUsd: 0.0078,
        children: [
          {
            id: "sp_guard_01",
            traceId: "tr_8f9104b2a3c7",
            parentSpanId: "sp_root_01",
            name: "Input Safety & PII Redaction",
            type: "guardrail",
            status: "ok",
            startTime: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
            durationMs: 45,
            attributes: { safety_passed: true, pii_detected: false },
          },
          {
            id: "sp_retriever_01",
            traceId: "tr_8f9104b2a3c7",
            parentSpanId: "sp_root_01",
            name: "KnowledgeBase.search_policy",
            type: "retriever",
            status: "ok",
            startTime: new Date(Date.now() - 1000 * 60 * 3 + 45).toISOString(),
            durationMs: 120,
            input: { query: "annual subscription refund grace period policy" },
            output: { chunks_retrieved: 3, top_score: 0.94 },
          },
          {
            id: "sp_llm_01",
            traceId: "tr_8f9104b2a3c7",
            parentSpanId: "sp_root_01",
            name: "LLM Call: Plan Action",
            type: "llm",
            status: "ok",
            startTime: new Date(Date.now() - 1000 * 60 * 3 + 165).toISOString(),
            durationMs: 460,
            model: "gpt-4o",
            promptTokens: 820,
            completionTokens: 120,
            totalTokens: 940,
            costUsd: 0.0044,
            input: { prompt: "System: You are an enterprise support agent... Tool call required: verify_eligibility" },
            output: { tool_calls: [{ name: "stripe_verify_invoice", args: { account_id: "acc_992138" } }] },
          },
          {
            id: "sp_tool_01",
            traceId: "tr_8f9104b2a3c7",
            parentSpanId: "sp_root_01",
            name: "Stripe API: Get Recent Charges",
            type: "tool",
            status: "ok",
            startTime: new Date(Date.now() - 1000 * 60 * 3 + 625).toISOString(),
            durationMs: 140,
            input: { endpoint: "/v1/charges", account: "acc_992138" },
            output: { charge_id: "ch_3PqL", amount: 24000, days_ago: 2 },
          },
          {
            id: "sp_llm_02",
            traceId: "tr_8f9104b2a3c7",
            parentSpanId: "sp_root_01",
            name: "LLM Call: Generate Response",
            type: "llm",
            status: "ok",
            startTime: new Date(Date.now() - 1000 * 60 * 3 + 765).toISOString(),
            durationMs: 175,
            model: "gpt-4o",
            promptTokens: 420,
            completionTokens: 260,
            totalTokens: 680,
            costUsd: 0.0034,
            output: { text: "I've checked your account. Since your renewal was processed 2 days ago..." },
          },
        ],
      },
    ],
  },
  {
    id: "tr_a12b9843fe21",
    name: "Financial Synthesizer / Monthly GAAP Variance",
    agentId: "agent_sql_analyst",
    agentName: "Financial Data Synthesizer",
    sessionId: "sess_finance_882",
    userId: "usr_sarah_cfo",
    status: "error",
    startTime: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    durationMs: 3820,
    promptTokens: 3890,
    completionTokens: 540,
    totalTokens: 4430,
    totalCostUsd: 0.0248,
    tags: ["production", "finance", "sql-agent", "timeout-risk"],
    input: {
      query: "Analyze departmental SaaS spend variances between Q3 and Q4 with breakdown by vendor",
    },
    output: {
      error: "QueryExecutionError: Connection to Snowflake warehouse timeout after 3000ms",
    },
    metadata: {
      warehouse: "FINANCE_WH_LARGE",
      cluster: "snowflake-us-east-1",
    },
    spans: [
      {
        id: "sp_root_02",
        traceId: "tr_a12b9843fe21",
        parentSpanId: null,
        name: "Financial Analysis Workflow",
        type: "agent",
        status: "error",
        startTime: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
        durationMs: 3820,
        totalTokens: 4430,
        costUsd: 0.0248,
        children: [
          {
            id: "sp_llm_sql_gen",
            traceId: "tr_a12b9843fe21",
            parentSpanId: "sp_root_02",
            name: "LLM Call: Synthesize SQL Statement",
            type: "llm",
            status: "ok",
            startTime: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
            durationMs: 780,
            model: "claude-3-5-sonnet",
            promptTokens: 2900,
            completionTokens: 380,
            totalTokens: 3280,
            costUsd: 0.0182,
            output: { sql: "SELECT department, vendor_name, SUM(amount) FROM saas_ledger WHERE quarter IN ('Q3', 'Q4')..." },
          },
          {
            id: "sp_tool_sql_exec",
            traceId: "tr_a12b9843fe21",
            parentSpanId: "sp_root_02",
            name: "Snowflake Driver: Execute Query",
            type: "tool",
            status: "error",
            startTime: new Date(Date.now() - 1000 * 60 * 12 + 780).toISOString(),
            durationMs: 3040,
            error: {
              message: "ETIMEDOUT: Connection to warehouse timed out after 3000ms retry limit exceeded",
              code: "ERR_QUERY_TIMEOUT",
              stack: "SnowflakeClient.query() at /app/services/snowflake.py:142\nWarehouseTimeoutException: 3000ms exceeded",
            },
          },
        ],
      },
    ],
  },
  {
    id: "tr_bb4910ef6731",
    name: "Coding Swarm / Pull Request Lint & Security Scan",
    agentId: "agent_code_reviewer",
    agentName: "Autonomous Coding Swarm",
    sessionId: "sess_gh_action_142",
    userId: "usr_ci_bot",
    status: "ok",
    startTime: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    durationMs: 2450,
    promptTokens: 5800,
    completionTokens: 1100,
    totalTokens: 6900,
    totalCostUsd: 0.0138,
    tags: ["ci-cd", "deepseek-r1", "security-check"],
    input: { pr_number: 481, repository: "corp/backend-api", diff_lines: 480 },
    output: { issues_found: 0, status: "approved", comment: "No vulnerabilities detected in dependencies or authentication flow." },
  },
  {
    id: "tr_cc31940a28f7",
    name: "Customer Support / Multi-step Diagnostics",
    agentId: "agent_customer_support",
    agentName: "Customer Support Agent",
    sessionId: "sess_user_7718",
    userId: "usr_elena_v",
    status: "running",
    startTime: new Date(Date.now() - 1000 * 15).toISOString(),
    durationMs: 15400,
    promptTokens: 2100,
    completionTokens: 180,
    totalTokens: 2280,
    totalCostUsd: 0.0094,
    tags: ["live-stream", "troubleshooting"],
    input: { message: "My webhook payload signature verification is failing consistently with 401 Unauthorized" },
    output: null,
  },
  {
    id: "tr_dd9920b134aa",
    name: "Vector Retrieval / Policy Ingestion Chunking",
    agentId: "agent_doc_retriever",
    agentName: "Vector Retrieval Agent",
    sessionId: "sess_kb_worker_01",
    userId: "usr_system",
    status: "ok",
    startTime: new Date(Date.now() - 1000 * 60 * 42).toISOString(),
    durationMs: 310,
    promptTokens: 840,
    completionTokens: 0,
    totalTokens: 840,
    totalCostUsd: 0.0001,
    tags: ["embeddings", "background-worker"],
    input: { document_id: "doc_compliance_2026.pdf", chunks: 14 },
    output: { vectors_written: 14, collection: "kb_policies" },
  },
]

export const MOCK_KPIS: OverviewKPIs = {
  totalTraces: 5274,
  totalTracesDeltaPct: 14.2,
  errorRate: 0.021, // 2.1%
  errorRateDeltaPct: -0.8,
  p50LatencyMs: 480,
  p50LatencyDeltaPct: -5.4,
  p95LatencyMs: 1840,
  p95LatencyDeltaPct: -12.1,
  totalTokens: 19320000,
  totalTokensDeltaPct: 18.6,
  totalCostUsd: 61.70,
  totalCostDeltaPct: 8.3,
  sparklines: {
    traces: [380, 420, 510, 490, 560, 620, 710, 680, 740, 810, 860, 920],
    errorRate: [3.4, 3.1, 2.8, 2.9, 2.6, 2.5, 2.3, 2.4, 2.1, 2.2, 2.0, 2.1],
    latency: [540, 520, 510, 495, 510, 480, 475, 490, 465, 480, 470, 480],
    tokens: [1.1, 1.2, 1.3, 1.4, 1.5, 1.7, 1.8, 1.9, 2.0, 2.1, 2.3, 2.4],
    cost: [3.8, 4.1, 4.5, 4.7, 5.0, 5.2, 5.8, 5.9, 6.1, 6.4, 6.7, 7.1],
  },
}
